# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-23 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charlas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariovotomodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
